### PR TITLE
Bring down MSRV to rust 1.41.0

### PR DESCRIPTION
**Pull request by kcalvinalvin**
These commits that are required to bring rustreexo into the rust bitcoin organization as MSRV of 1.41.0 is required for rust-bitcoin.

### CODE REVIEW

**Comment by kcalvinalvin** [comment]
Pinging @Davidson-Souza for review.

**Comment by Davidson-Souza** [comment]
Tested ack 9c268d2.

**Comment by kcalvinalvin** [comment]
re-requesting @Davidson-Souza for review as merging #11 required a few more changes.

**Comment by Davidson-Souza** [comment]
ack 6829cc29. Can confirm the changes are required by reverting then and trying to compile. With the changes, it works.

**Pull request merged**
